name: edu_chatbot

services:
  data-ingest:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile  # reuse the same backend Dockerfile
    ports:
      - "8001:8000"
    command: python -m src.backend.api.main_data_ingest  # override the default start
    environment:
      - PYTHONPATH=/app
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - chroma-server
  chroma-server:
    image: chromadb/chroma:latest
    command: run --host 0.0.0.0 --path /data
    ports:
      - "8002:8000"
    volumes:
      - chroma-data:/data
    networks:
      - app-network
    restart: unless-stopped
  backend:
    build:
      context: .  # all files in the current directory are available for build
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./data:/app/data 
    restart: unless-stopped
    networks:
      - app-network
    # depends_on:
    #   - chroma-server
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
volumes:
  chroma-data:
networks:
  app-network:
    driver: bridge