services:
  - type: web
    name: chat-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.backend.api.main
    rootDir: .
    envVars:
      - key: PYTHONPATH
        value: /app
        
  - type: web
    name: data-ingest-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.backend.api.main_data_ingest
    rootDir: .
    envVars:
      - key: PYTHONPATH
        value: /app

  - type: web
    name: chroma-server
    env: docker
    region: oregon
    plan: starter
    buildCommand: ""
    dockerfilePath: chroma-server/Dockerfile
    healthCheckPath: /

  - type: web
    name: edu-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: src/frontend/build
    rootDir: src/frontend

  # - type: web
  #   name: gradio-tool-ui
  #   env: python
  #   buildCommand: pip install -r requirements.txt
  #   startCommand: python -m src.creator.app
  #   rootDir: .
  #   disk:
  #     name: chromadb
  #     mountPath: /mnt/data/embeddings
  #     sizeGB: 1
